/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GamesRouteImport } from './routes/games'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as WeekWeekNumberRouteImport } from './routes/week.$weekNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekNumberRoute = WeekWeekNumberRouteImport.update({
  id: '/week/$weekNumber',
  path: '/week/$weekNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/picks': typeof PicksRoute
  '/roster': typeof RosterRoute
  '/week/$weekNumber': typeof WeekWeekNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/picks': typeof PicksRoute
  '/roster': typeof RosterRoute
  '/week/$weekNumber': typeof WeekWeekNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/games': typeof GamesRoute
  '/picks': typeof PicksRoute
  '/roster': typeof RosterRoute
  '/week/$weekNumber': typeof WeekWeekNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/desk' | '/games' | '/picks' | '/roster' | '/week/$weekNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/desk' | '/games' | '/picks' | '/roster' | '/week/$weekNumber'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/games'
    | '/picks'
    | '/roster'
    | '/week/$weekNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  GamesRoute: typeof GamesRoute
  PicksRoute: typeof PicksRoute
  RosterRoute: typeof RosterRoute
  WeekWeekNumberRoute: typeof WeekWeekNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$weekNumber': {
      id: '/week/$weekNumber'
      path: '/week/$weekNumber'
      fullPath: '/week/$weekNumber'
      preLoaderRoute: typeof WeekWeekNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  GamesRoute: GamesRoute,
  PicksRoute: PicksRoute,
  RosterRoute: RosterRoute,
  WeekWeekNumberRoute: WeekWeekNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
